### ISSUE TITLE
Duplicate Initialization

### ISSUE THREAD

**Issue by xiaxin1998** [ssui-liu/learnable-embed-sizes-for-RecSys#2]
Hello, thank you for sharing the codes. I have one question.
In init function of class engine, you use setup_factorizer(opt) function  where there will be a initialization of self.model. 
Then in train_an_episode function, you call self._factorizer.init_episode() function to init self.model. 
Why you init self.model twice? Is that a duplication?

https://github.com/ssui-liu/learnable-embed-sizes-for-RecSys/blob/e4d07d2c5e4aaefa95b939b83600adfaf47d7a6f/engine.py#L150

**Comment by ssui-liu** [comment]
Hello:
Yes, it was used to re-initialize the factorizer when we needed to run multiple episodes to find the best hyperparameters.

**Comment by xiaxin1998** [comment]
Thanks for your reply. I got it.
Another question is why not prune item embeddings instead of feature embeddings? Have you thought about the large number of items in recommender systems?

**Comment by ssui-liu** [comment]
As far as I concerned, pruning feature embedding can work better than pruning on item embeddings due to the redundancy in features. Pruning out some less influence features may have less influence on model's performance compared with drop off item embeddings. Hence, pruning features can save more memory usages.
